### ISSUE TITLE
Output TIFF black dots

### ISSUE THREAD

**Issue by Dodgeyelectronics** [Signynt/signynts-darkroom-script#3]
When I try running the script with pythonh using the test file, I end up with a TIFF file that has black dots where the dust and small bright highlights were instead of a file with dust and scratches removed.

[
<img width="641" alt="Screenshot 2024-03-21 at 09 58 47" src="https://github.com/Signynt/signynts-darkroom-script/assets/88434248/39e27e9f-9672-4adb-a817-1893ebe1bfa0">
](url)

There are no errors while the script is running, everything appears to be working as it should...

**Comment by Signynt** [comment]
That is intentional, the output file is a tiff with an alpha layer, showing where the dust was detected. This gets rendered as if the dust spots were missing, but they’re actually still present in the file.
To remove the dust, open the file in Affinity Photo or Photoshop, and use the provided macro to remove the dust.
